import { RouteInfo } from "./sidebar.metadata";

export const ROUTES: RouteInfo[] = [
  {
    path: "/dashboard",
    title: "Tableau de bord",
    icon: "bi bi-speedometer2",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/childManager",
    title: "Gestion des enfants",
    icon: "bi bi-clipboard2-plus",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/listChilds",
    title: "Liste des enfants",
    icon: "bi bi-list-task",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/childProjcts",
    title: "Projets des enfants",
    icon: "bi bi-list-stars",
    class: "",
    extralink: false,
    submenu: [],
    // <i class="fa-solid fa-cake-candles"></i>
  },
  {
    path: "/component/allMonthAnniv",
    title: "Anniversaires du mois",
    icon: "bi bi-palette",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/allActivity",
    title: "Activitées de l'année",
    icon: "bi bi-clipboard-data",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/component/childLog",
    title: "Journal",
    icon: "bi bi-card-text",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/about",
    title: "A propos",
    icon: "bi bi-info-circle",
    class: "",
    extralink: false,
    submenu: [],
  },
  // {
  //   path: "/component/dropdown",
  //   title: "Dropdown",
  //   icon: "bi bi-menu-app",
  //   class: "",
  //   extralink: false,
  //   submenu: [],
  // },
  // {
  //   path: "/component/table",
  //   title: "Table",
  //   icon: "bi bi-layout-split",
  //   class: "",
  //   extralink: false,
  //   submenu: [],
  // },
  // {
  //   path: "/about",
  //   title: "About",
  //   icon: "bi bi-people",
  //   class: "",
  //   extralink: false,
  //   submenu: [],
  // },
];
